"""Orders that need a human (#193 — beta hardening, task 193.3).

Polled by the `prod-monitor` GitHub Action. In the beta, paid custom packs are
generated by a session worker on the founder's Mac; when that worker is down
nothing consumes the queue and nothing runs the stuck-order sweep either (it
lives in the same worker process), so an order would sit forever with nobody
told. This endpoint is the outside view that still works then.

Admin-only, and deliberately minimal output: ids, states and ages — never the
customer's prompt or account id — because the monitor's logs are public.
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime, timedelta
from typing import Annotated

from fastapi import APIRouter, Depends, Query
from pydantic import BaseModel
from sqlalchemy import func, or_, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.models.job import GenerationJob
from app.db.models.order import GenerationOrder
from app.db.session import get_session

from ..deps import require_admin

router = APIRouter(prefix="/v1/admin", tags=["admin"], dependencies=[Depends(require_admin)])


class AttentionOrder(BaseModel):
    id: uuid.UUID
    status: str
    job_status: str | None
    # Minutes since the last sign of life (queue handoff or job heartbeat).
    idle_minutes: int


class OrdersAttentionResponse(BaseModel):
    stuck: list[AttentionOrder]
    refund_eligible: list[AttentionOrder]


@router.get("/orders/attention", response_model=OrdersAttentionResponse)
async def orders_needing_attention(
    session: Annotated[AsyncSession, Depends(get_session)],
    stuck_minutes: Annotated[int, Query(ge=5, le=1440)] = 30,
    refund_lookback_minutes: Annotated[int, Query(ge=5, le=10080)] = 120,
) -> OrdersAttentionResponse:
    """Orders with no sign of life for `stuck_minutes`, plus orders that went
    refund-eligible within the last `refund_lookback_minutes`.

    Liveness mirrors the worker sweep (`app.worker.sweep`): the later of the
    queue handoff (`enqueued_at`) and the job's `updated_at`, which the 60 s
    pipeline heartbeat keeps fresh. So a legitimately long pack run is never
    flagged, while a job parked in a queue no worker consumes is. The default 30 min sits well past the sweep's own
    thresholds (3 / 15 min): anything still stuck by then means the sweep did
    not run, i.e. no worker is alive.

    Refund-eligible is a window, not a flag, because the monitor is stateless.
    Only still-'failed' orders count: `refund_eligible` is never cleared, so a
    retried (or retried-and-delivered) order would otherwise keep alerting.
    A failed order's job is terminal and no longer written, so its
    `updated_at` dates the failure that set the flag.
    """
    now = datetime.now(UTC)
    # Postgres GREATEST skips NULLs, so an order without a job falls back to
    # its queue handoff.
    last_alive = func.greatest(GenerationJob.updated_at, GenerationOrder.enqueued_at)
    base = select(
        GenerationOrder.id, GenerationOrder.status, GenerationJob.status, last_alive
    ).outerjoin(GenerationJob, GenerationJob.id == GenerationOrder.job_id)

    stuck_stmt = base.where(
        GenerationOrder.status.in_(("pending", "in_progress")),
        or_(GenerationJob.status.is_(None), GenerationJob.status != "done"),
        last_alive < now - timedelta(minutes=stuck_minutes),
    )
    refund_stmt = base.where(
        GenerationOrder.refund_eligible.is_(True),
        GenerationOrder.status == "failed",
        last_alive >= now - timedelta(minutes=refund_lookback_minutes),
    )

    def _rows(result) -> list[AttentionOrder]:
        return [
            AttentionOrder(
                id=order_id,
                status=status,
                job_status=job_status,
                idle_minutes=int((now - alive).total_seconds() // 60),
            )
            for order_id, status, job_status, alive in result
        ]

    return OrdersAttentionResponse(
        stuck=_rows(await session.execute(stuck_stmt)),
        refund_eligible=_rows(await session.execute(refund_stmt)),
    )
