"""Orders that need a human (#193 — beta hardening, task 193.3).

Polled by the `prod-monitor` GitHub Action. In the beta, paid custom packs are
generated by a session worker on the founder's Mac; when that worker is down
nothing consumes the queue and nothing runs the stuck-order sweep either (it
lives in the same worker process), so an order would sit forever with nobody
told. This endpoint is the outside view that still works then.

Admin-only, and deliberately minimal output: ids, states and ages — never the
customer's prompt or account id — because the monitor's logs are public.
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime, timedelta
from typing import Annotated

from arq.connections import ArqRedis
from arq.constants import default_queue_name, health_check_key_suffix
from fastapi import APIRouter, Depends, Query
from pydantic import BaseModel
from sqlalchemy import func, or_, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import WORKER_HEALTH_CHECK_INTERVAL_S, Settings, get_settings
from app.db.models.job import GenerationJob
from app.db.models.order import GenerationOrder
from app.db.session import get_session

from ..deps import get_arq_pool, require_admin

router = APIRouter(prefix="/v1/admin", tags=["admin"], dependencies=[Depends(require_admin)])


class AttentionOrder(BaseModel):
    id: uuid.UUID
    status: str
    job_status: str | None
    # Minutes since the last sign of life (queue handoff or job heartbeat).
    idle_minutes: int


class OrdersAttentionResponse(BaseModel):
    stuck: list[AttentionOrder]
    refund_eligible: list[AttentionOrder]


@router.get("/orders/attention", response_model=OrdersAttentionResponse)
async def orders_needing_attention(
    session: Annotated[AsyncSession, Depends(get_session)],
    stuck_minutes: Annotated[int, Query(ge=5, le=1440)] = 30,
    refund_lookback_minutes: Annotated[int, Query(ge=5, le=10080)] = 120,
) -> OrdersAttentionResponse:
    """Orders with no sign of life for `stuck_minutes`, plus orders that went
    refund-eligible within the last `refund_lookback_minutes`.

    Liveness mirrors the worker sweep (`app.worker.sweep`): the later of the
    queue handoff (`enqueued_at`) and the job's `updated_at`, which the 60 s
    pipeline heartbeat keeps fresh. So a legitimately long pack run is never
    flagged, while a job parked in a queue no worker consumes is. The default 30 min sits well past the sweep's own
    thresholds (3 / 15 min): anything still stuck by then means the sweep did
    not run, i.e. no worker is alive.

    Refund-eligible is a window, not a flag, because the monitor is stateless.
    Only still-'failed' orders count: `refund_eligible` is never cleared, so a
    retried (or retried-and-delivered) order would otherwise keep alerting.
    A failed order's job is terminal and no longer written, so its
    `updated_at` dates the failure that set the flag.
    """
    now = datetime.now(UTC)
    # Postgres GREATEST skips NULLs, so an order without a job falls back to
    # its queue handoff.
    last_alive = func.greatest(GenerationJob.updated_at, GenerationOrder.enqueued_at)
    base = select(
        GenerationOrder.id, GenerationOrder.status, GenerationJob.status, last_alive
    ).outerjoin(GenerationJob, GenerationJob.id == GenerationOrder.job_id)

    stuck_stmt = base.where(
        GenerationOrder.status.in_(("pending", "in_progress")),
        or_(GenerationJob.status.is_(None), GenerationJob.status != "done"),
        last_alive < now - timedelta(minutes=stuck_minutes),
    )
    refund_stmt = base.where(
        GenerationOrder.refund_eligible.is_(True),
        GenerationOrder.status == "failed",
        last_alive >= now - timedelta(minutes=refund_lookback_minutes),
    )

    # #193: the beta's one session worker runs one pack at a time, for an hour
    # or more, and the orders queued behind it show no life of their own. They
    # only need a human when nothing is alive to get to them: a worker that
    # touched a job (heartbeat, step) after that job's queue handoff within the
    # window is alive. The API's own writes (create, /retry) land together with
    # the handoff stamp, so they never count as a worker.
    worker_alive = await session.scalar(
        select(GenerationJob.id)
        .join(GenerationOrder, GenerationOrder.job_id == GenerationJob.id)
        .where(
            GenerationJob.updated_at >= now - timedelta(minutes=stuck_minutes),
            GenerationJob.updated_at > GenerationOrder.enqueued_at + timedelta(seconds=30),
        )
        .limit(1)
    )

    def _rows(result) -> list[AttentionOrder]:
        return [
            AttentionOrder(
                id=order_id,
                status=status,
                job_status=job_status,
                idle_minutes=int((now - alive).total_seconds() // 60),
            )
            for order_id, status, job_status, alive in result
        ]

    return OrdersAttentionResponse(
        stuck=[] if worker_alive else _rows(await session.execute(stuck_stmt)),
        refund_eligible=_rows(await session.execute(refund_stmt)),
    )


class WorkerHeartbeatResponse(BaseModel):
    # The queue orders are routed to (ORDER_QUEUE_NAME).
    queue_name: str
    # True when that is a session queue (beta: the mba worker). Only then must a
    # worker be alive: on ARQ's default queue the Fly worker serves orders, and
    # while the session queue is in use that machine is stopped on purpose.
    session_queue: bool
    # Seconds since the queue's worker last wrote its heartbeat; None = no
    # heartbeat (no worker consuming the queue for over a minute).
    heartbeat_age_s: int | None


@router.get("/worker/heartbeat", response_model=WorkerHeartbeatResponse)
async def worker_heartbeat(
    settings: Annotated[Settings, Depends(get_settings)],
    redis: Annotated[ArqRedis, Depends(get_arq_pool)],
) -> WorkerHeartbeatResponse:
    """Liveness of the worker consuming the order queue (#193).

    Orders alone cannot tell a dead worker apart from a quiet day: the mba
    worker once lay dead ~20 h with nothing queued, so nobody was told. ARQ
    rewrites `<queue>:health-check` every WORKER_HEALTH_CHECK_INTERVAL_S with a
    TTL of interval + 1 s, so the remaining TTL dates the last write and a
    missing key means no worker.
    """
    queue = settings.order_queue_name
    ttl_ms = await redis.pttl(queue + health_check_key_suffix)
    age: int | None = None
    if ttl_ms >= 0:
        # A worker still on ARQ's 1 h default (pre-#193 code) leaves a longer
        # TTL: it was alive within the hour, so report it fresh; its key still
        # expires within an hour of its death, so the alert comes, just later.
        age = max(0, WORKER_HEALTH_CHECK_INTERVAL_S + 1 - ttl_ms // 1000)
    return WorkerHeartbeatResponse(
        queue_name=queue,
        session_queue=queue != default_queue_name,
        heartbeat_age_s=age,
    )
