//
//  EarconToneTests.swift
//  HangsTests
//
//  Issue #184 track E — the earcons moved off `AudioServicesPlaySystemSound`
//  (system-sound channel: ringer-scoped, swallowed on a car A2DP route, so the
//  founder heard no acknowledgement at all while driving) onto AVAudioPlayer
//  over the app's shared session, fed by tones synthesized in memory.
//
//  Only the PURE generator is tested — AVAudioPlayer needs an audio device the
//  simulator test host does not meaningfully have. What matters here is that
//  the bytes it is handed are a WAV it can actually decode, and that each cue
//  keeps the duration it was designed with (a cue that silently shortens to
//  nothing is inaudible in exactly the car the fix is for).
//

import Foundation
@testable import Hangs
import Testing

@Suite("EarconTone")
struct EarconToneTests {

    /// WHY: `AVAudioPlayer(data:)` parses the container, so a malformed header
    /// means the cue silently falls back to the system sound — i.e. straight
    /// back to the #184 bug, with no crash to notice it by.
    @Test("The generated bytes are a canonical mono 16-bit PCM RIFF/WAVE file")
    func producesValidRIFFHeader() {
        let data = EarconTone.wavData(for: .micLive)
        #expect(data.count > 44)

        func ascii(_ range: Range<Int>) -> String {
            String(decoding: data[range], as: UTF8.self)
        }
        func uint32(at offset: Int) -> UInt32 {
            data[offset ..< offset + 4].reversed().reduce(UInt32(0)) { $0 << 8 | UInt32($1) }
        }
        func uint16(at offset: Int) -> UInt16 {
            data[offset ..< offset + 2].reversed().reduce(UInt16(0)) { $0 << 8 | UInt16($1) }
        }

        #expect(ascii(0 ..< 4) == "RIFF")
        #expect(ascii(8 ..< 12) == "WAVE")
        #expect(ascii(12 ..< 16) == "fmt ")
        #expect(ascii(36 ..< 40) == "data")
        #expect(uint16(at: 20) == 1, "PCM, uncompressed")
        #expect(uint16(at: 22) == 1, "mono")
        #expect(uint32(at: 24) == 44100)
        #expect(uint16(at: 34) == 16, "16-bit samples")
        // The two declared sizes must agree with the payload, or the decoder
        // truncates the cue.
        #expect(Int(uint32(at: 4)) == data.count - 8)
        #expect(Int(uint32(at: 40)) == data.count - 44)
    }

    /// WHY: the cue's LENGTH is its design (two 70 ms steps). A regression that
    /// halves it makes it unhearable over road noise, which a test that only
    /// checks the file parses cannot see. #188 G6: the other cues have no tone
    /// at all, so their generator output must be empty, not a stray blip.
    @Test("The mic-live cue carries its designed sample count; haptic-only cues have none")
    func cueDurations() {
        let rate = EarconTone.sampleRate
        func samples(_ earcon: Earcon) -> Int {
            (EarconTone.wavData(for: earcon).count - 44) / 2
        }
        #expect(samples(.micLive) == 2 * Int((0.070 * rate).rounded()))
        for earcon in Earcon.allCases where !earcon.hasTone {
            #expect(samples(earcon) == 0, "\(earcon) is haptic-only and must have no tone")
        }
    }

    /// WHY (#185 track F, founder 2026-09-24): the tones were loud and grew
    /// tiresome over a quiz. The remaining tone plays at no more than a quarter
    /// of full scale (6 dB under the old half scale).
    @Test("The mic-live cue is at most quarter scale")
    func cuesAreQuiet() {
        let data = EarconTone.wavData(for: .micLive)
        let peak = stride(from: 44, to: data.count, by: 2).map { offset in
            abs(Int(Int16(bitPattern: UInt16(data[offset]) | UInt16(data[offset + 1]) << 8)))
        }.max() ?? 0
        #expect(peak <= Int(0.25 * Double(Int16.max)) + 1, "mic-live is louder than quarter scale")
    }

    /// WHY (#185 track F): every cue has a haptic now, and the recording cues
    /// — mic open, speech heard, mic closed — fire on EVERY question, so they
    /// must be the soft generator: a firm tap that often becomes a buzz the
    /// driver learns to ignore.
    /// #188 G5 (founder 2026-10-06): a skip is not an error, so the skip cue
    /// taps softly too — the warning buzz it had read as "you did wrong".
    @Test("Recording and skip cues tap softly; the command ack keeps its firmer tap")
    func haptics() {
        // Every cue, tone or not, still has its haptic (#188 G6 kept them all).
        for earcon in [Earcon.micLive, .speechStart, .gotIt, .skipConfirm] {
            guard case let .soft(intensity) = EarconHaptic.haptic(for: earcon) else {
                Issue.record("\(earcon) must use the soft generator")
                continue
            }
            #expect(intensity > 0 && intensity < 1)
        }
        #expect(EarconHaptic.haptic(for: .commandAck) == .light)
    }

    /// WHY: a waveform that starts or ends mid-cycle clicks, and on a car
    /// speaker the click is louder than the tone. The fade is what removes it,
    /// so the first and last samples of a tone must be at (or next to) zero
    /// while the body reaches the designed peak.
    @Test("Tones fade in and out and reach the designed peak")
    func fadeAndPeak() {
        let data = EarconTone.wavData(for: .micLive)
        let samples: [Int16] = stride(from: 44, to: data.count, by: 2).map { offset in
            Int16(bitPattern: UInt16(data[offset]) | UInt16(data[offset + 1]) << 8)
        }
        #expect(samples.first == 0)
        #expect(samples.last == 0)
        let peak = samples.map { abs(Int($0)) }.max() ?? 0
        let expected = Int(EarconTone.peak * Double(Int16.max))
        #expect(peak <= expected + 1, "must never clip")
        #expect(peak > expected * 9 / 10, "…but must actually reach the designed level")
    }
}
