//
//  EarconToneTests.swift
//  HangsTests
//
//  Issue #184 track E — the earcons moved off `AudioServicesPlaySystemSound`
//  (system-sound channel: ringer-scoped, swallowed on a car A2DP route, so the
//  founder heard no acknowledgement at all while driving) onto AVAudioPlayer
//  over the app's shared session, fed by tones synthesized in memory.
//
//  Only the PURE generator is tested — AVAudioPlayer needs an audio device the
//  simulator test host does not meaningfully have. What matters here is that
//  the bytes it is handed are a WAV it can actually decode, and that each cue
//  keeps the duration it was designed with (a cue that silently shortens to
//  nothing is inaudible in exactly the car the fix is for).
//

import Foundation
@testable import Hangs
import Testing

@Suite("EarconTone")
struct EarconToneTests {

    /// WHY: `AVAudioPlayer(data:)` parses the container, so a malformed header
    /// means the cue silently falls back to the system sound — i.e. straight
    /// back to the #184 bug, with no crash to notice it by.
    @Test("The generated bytes are a canonical mono 16-bit PCM RIFF/WAVE file")
    func producesValidRIFFHeader() {
        let data = EarconTone.wavData(for: .commandAck)
        #expect(data.count > 44)

        func ascii(_ range: Range<Int>) -> String {
            String(decoding: data[range], as: UTF8.self)
        }
        func uint32(at offset: Int) -> UInt32 {
            data[offset ..< offset + 4].reversed().reduce(UInt32(0)) { $0 << 8 | UInt32($1) }
        }
        func uint16(at offset: Int) -> UInt16 {
            data[offset ..< offset + 2].reversed().reduce(UInt16(0)) { $0 << 8 | UInt16($1) }
        }

        #expect(ascii(0 ..< 4) == "RIFF")
        #expect(ascii(8 ..< 12) == "WAVE")
        #expect(ascii(12 ..< 16) == "fmt ")
        #expect(ascii(36 ..< 40) == "data")
        #expect(uint16(at: 20) == 1, "PCM, uncompressed")
        #expect(uint16(at: 22) == 1, "mono")
        #expect(uint32(at: 24) == 44100)
        #expect(uint16(at: 34) == 16, "16-bit samples")
        // The two declared sizes must agree with the payload, or the decoder
        // truncates the cue.
        #expect(Int(uint32(at: 4)) == data.count - 8)
        #expect(Int(uint32(at: 40)) == data.count - 44)
    }

    /// WHY: each cue's LENGTH is its design — the rising/falling pairs are two
    /// 70 ms steps, the destructive warning is two 90 ms tones around a 40 ms
    /// gap, the command ack is one 60 ms blip. A regression that halves a cue
    /// makes it unhearable over road noise, which is undetectable from a test
    /// that only checks the file parses.
    @Test("Each cue carries its designed sample count")
    func cueDurations() {
        let rate = EarconTone.sampleRate
        func samples(_ earcon: Earcon) -> Int {
            (EarconTone.wavData(for: earcon).count - 44) / 2
        }
        #expect(samples(.commandAck) == Int((0.060 * rate).rounded()))
        #expect(samples(.micLive) == 2 * Int((0.070 * rate).rounded()))
        #expect(samples(.gotIt) == samples(.micLive), "gotIt is micLive mirrored, same length")
        #expect(samples(.skipConfirm) == 2 * Int((0.090 * rate).rounded()) + Int((0.040 * rate).rounded()))
        #expect(samples(.speechStart) == Int((0.050 * rate).rounded()))
    }

    /// WHY (#185 track F, founder 2026-09-24): the tones were loud and grew
    /// tiresome over a quiz. Every cue plays at no more than a quarter of full
    /// scale (6 dB under the old half scale), and the speech-start tone — it
    /// plays while the driver is TALKING — is the quietest of all.
    @Test("Every cue is at most quarter scale; speech-start is the quietest")
    func cuesAreQuiet() {
        func peak(_ earcon: Earcon) -> Int {
            let data = EarconTone.wavData(for: earcon)
            return stride(from: 44, to: data.count, by: 2).map { offset in
                abs(Int(Int16(bitPattern: UInt16(data[offset]) | UInt16(data[offset + 1]) << 8)))
            }.max() ?? 0
        }
        let quarter = Int(0.25 * Double(Int16.max)) + 1
        for earcon in Earcon.allCases {
            #expect(peak(earcon) <= quarter, "\(earcon) is louder than quarter scale")
        }
        for earcon in Earcon.allCases where earcon != .speechStart {
            #expect(peak(.speechStart) < peak(earcon), "speech-start must be quieter than \(earcon)")
        }
    }

    /// WHY (#185 track F): every cue has a haptic now, and the recording cues
    /// — mic open, speech heard, mic closed — fire on EVERY question, so they
    /// must be the soft generator: a firm tap that often becomes a buzz the
    /// driver learns to ignore.
    @Test("Recording cues tap softly; command cues keep their firmer haptics")
    func haptics() {
        for earcon in [Earcon.micLive, .speechStart, .gotIt] {
            guard case let .soft(intensity) = EarconHaptic.haptic(for: earcon) else {
                Issue.record("\(earcon) must use the soft generator")
                continue
            }
            #expect(intensity > 0 && intensity < 1)
        }
        #expect(EarconHaptic.haptic(for: .commandAck) == .light)
        #expect(EarconHaptic.haptic(for: .skipConfirm) == .warning)
    }

    /// WHY: a waveform that starts or ends mid-cycle clicks, and on a car
    /// speaker the click is louder than the tone. The fade is what removes it,
    /// so the first and last samples of a tone must be at (or next to) zero
    /// while the body reaches the designed peak.
    @Test("Tones fade in and out and reach the designed peak")
    func fadeAndPeak() {
        let data = EarconTone.wavData(for: .commandAck)
        let samples: [Int16] = stride(from: 44, to: data.count, by: 2).map { offset in
            Int16(bitPattern: UInt16(data[offset]) | UInt16(data[offset + 1]) << 8)
        }
        #expect(samples.first == 0)
        #expect(samples.last == 0)
        let peak = samples.map { abs(Int($0)) }.max() ?? 0
        let expected = Int(EarconTone.peak * Double(Int16.max))
        #expect(peak <= expected + 1, "must never clip")
        #expect(peak > expected * 9 / 10, "…but must actually reach the designed level")
    }

    /// WHY: the gap is what makes skipConfirm read as a WARNING (two separate
    /// taps) rather than one long tone — the shape is the only thing the driver
    /// can use, since they cannot look.
    @Test("skipConfirm is two tones separated by real silence")
    func skipConfirmHasASilentGap() {
        let segments = EarconTone.segments(for: .skipConfirm)
        #expect(segments.count == 3)
        #expect(segments[1].frequency == nil, "the middle segment is silence")
        #expect(segments[0].frequency == segments[2].frequency)
    }
}
