"""Central LLM client factory — see ``factory`` module docstring (issue #53)."""

from .factory import (
    CRITIQUE,
    DIRECT,
    EMBED,
    EVAL,
    GEN,
    NORMALIZE,
    OPENROUTER,
    OPENROUTER_BASE_URL,
    PARSE,
    SCORE_GOOGLE,
    SCORE_OPENAI,
    TRANSLATE,
    VERIFY,
    chat_model,
    chat_openai,
    gateway,
    get_usage_handler,
    is_bedrock_model,
    openai_client,
    provider_for_model,
    resolve_model,
    set_usage_handler,
    supports_sampling_params,
)

__all__ = [
    "CRITIQUE",
    "DIRECT",
    "EMBED",
    "EVAL",
    "GEN",
    "NORMALIZE",
    "OPENROUTER",
    "OPENROUTER_BASE_URL",
    "PARSE",
    "SCORE_GOOGLE",
    "SCORE_OPENAI",
    "TRANSLATE",
    "VERIFY",
    "chat_model",
    "chat_openai",
    "gateway",
    "get_usage_handler",
    "is_bedrock_model",
    "openai_client",
    "provider_for_model",
    "resolve_model",
    "set_usage_handler",
    "supports_sampling_params",
]
