"""GET /api/v1/admin/orders/attention (#193 — beta hardening, task 193.3).

The prod-monitor GitHub Action fails (and so emails the founder) whenever this
endpoint lists anything. In the beta a paid order is generated by a session
worker on the founder's Mac; when it is down, the stuck-order sweep is down
with it, so this endpoint is the only thing that notices. The tests pin the
two properties that make the alert trustworthy: it fires for an order nobody
is working on, and it stays silent for a long but alive pack run (a false
alarm every night would train the founder to ignore it).
"""

from __future__ import annotations

import uuid
from collections.abc import AsyncIterator
from datetime import UTC, datetime, timedelta

import httpx
import pytest_asyncio
from app.api.v1.admin_orders import router as admin_orders_router
from app.config import Settings, get_settings
from app.db.models.job import GenerationJob
from app.db.models.order import GenerationOrder
from app.db.session import get_session
from fastapi import FastAPI
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession

from tests.api.conftest import TEST_ADMIN_KEY

URL = "/api/v1/admin/orders/attention"
ADMIN = {"X-Admin-Key": TEST_ADMIN_KEY}


@pytest_asyncio.fixture
async def admin_client(
    test_session: AsyncSession, _clean_orders: None
) -> AsyncIterator[httpx.AsyncClient]:
    async def _override_session() -> AsyncIterator[AsyncSession]:
        yield test_session

    app = FastAPI()
    app.include_router(admin_orders_router, prefix="/api")
    app.dependency_overrides[get_session] = _override_session
    app.dependency_overrides[get_settings] = lambda: Settings(admin_api_key=TEST_ADMIN_KEY)
    async with httpx.AsyncClient(
        transport=httpx.ASGITransport(app=app), base_url="http://test"
    ) as ac:
        yield ac


async def _order(
    session: AsyncSession,
    *,
    status: str,
    job_status: str,
    idle: timedelta,
    refund_eligible: bool = False,
) -> uuid.UUID:
    """Insert an order whose last sign of life (handoff + job heartbeat) was `idle` ago."""
    order = GenerationOrder(
        transaction_id=f"attention-{uuid.uuid4().hex}",
        product_id="pack_10",
        prompt="secret customer prompt",
        target_count=10,
        language="en",
        status=status,
        refund_eligible=refund_eligible,
        user_id="user-should-not-leak",
    )
    session.add(order)
    await session.flush()
    job = GenerationJob(order_id=order.id, status=job_status)
    session.add(job)
    await session.flush()
    order.job_id = job.id
    await session.commit()
    ts = datetime.now(UTC) - idle
    # Raw UPDATEs: the ORM's `onupdate` would stamp updated_at back to now().
    await session.execute(
        text("UPDATE generation_orders SET created_at = :ts, enqueued_at = :ts WHERE id = :id"),
        {"ts": ts, "id": order.id},
    )
    await session.execute(
        text("UPDATE generation_jobs SET updated_at = :ts WHERE id = :id"),
        {"ts": ts, "id": job.id},
    )
    await session.commit()
    return order.id


async def test_requires_admin_key(admin_client: httpx.AsyncClient) -> None:
    # Order states are ops data; only the monitor holding the key may read them.
    assert (await admin_client.get(URL)).status_code == 401


async def test_flags_orders_no_worker_is_touching(
    admin_client: httpx.AsyncClient, test_session: AsyncSession
) -> None:
    # Worker died mid-run: heartbeat stopped 45 min ago.
    dead = await _order(test_session, status="in_progress", job_status="generating", idle=timedelta(minutes=45))
    # Queued while the mba worker is off: never picked up.
    parked = await _order(test_session, status="in_progress", job_status="queued", idle=timedelta(minutes=40))
    never_enqueued = await _order(test_session, status="pending", job_status="queued", idle=timedelta(minutes=35))

    body = (await admin_client.get(URL, headers=ADMIN)).json()

    assert {o["id"] for o in body["stuck"]} == {str(dead), str(parked), str(never_enqueued)}
    assert all(o["idle_minutes"] >= 35 for o in body["stuck"])


async def test_silent_for_alive_or_finished_orders(
    admin_client: httpx.AsyncClient, test_session: AsyncSession
) -> None:
    # A multi-hour session-worker run is fine as long as its heartbeat ticks.
    await _order(test_session, status="in_progress", job_status="generating", idle=timedelta(minutes=2))
    # Terminal orders are never "stuck", however old.
    await _order(test_session, status="delivered", job_status="done", idle=timedelta(days=3))
    await _order(test_session, status="failed", job_status="failed", idle=timedelta(days=3))

    body = (await admin_client.get(URL, headers=ADMIN)).json()

    assert body == {"stuck": [], "refund_eligible": []}


async def test_refund_eligible_reported_once_within_window(
    admin_client: httpx.AsyncClient, test_session: AsyncSession
) -> None:
    # The monitor is stateless, so "just went refund-eligible" = inside the
    # lookback window; older ones must drop out or the alert never clears.
    fresh = await _order(test_session, status="failed", job_status="failed", idle=timedelta(minutes=10), refund_eligible=True)
    await _order(test_session, status="failed", job_status="failed", idle=timedelta(hours=5), refund_eligible=True)
    await _order(test_session, status="refunded", job_status="failed", idle=timedelta(minutes=10), refund_eligible=True)
    # The flag is never cleared: after POST /retry the order is re-run (fresh
    # job writes) or delivered, and is owed nothing — it must not alert.
    await _order(test_session, status="in_progress", job_status="generating", idle=timedelta(minutes=1), refund_eligible=True)
    await _order(test_session, status="delivered", job_status="done", idle=timedelta(minutes=5), refund_eligible=True)

    body = (await admin_client.get(URL, headers=ADMIN)).json()

    assert [o["id"] for o in body["refund_eligible"]] == [str(fresh)]
    assert body["stuck"] == []


async def test_output_carries_no_customer_data(
    admin_client: httpx.AsyncClient, test_session: AsyncSession
) -> None:
    # The monitor's workflow logs are public (public repo).
    await _order(test_session, status="in_progress", job_status="queued", idle=timedelta(hours=1))

    resp = await admin_client.get(URL, headers=ADMIN)

    assert set(resp.json()["stuck"][0]) == {"id", "status", "job_status", "idle_minutes"}
    assert "secret customer prompt" not in resp.text
    assert "user-should-not-leak" not in resp.text
